#!/bin/bash
# Script to check if the VSFTPD Virtual users necessary folders are there
# Author Bellamkonda Sudhakar
# Version 1.0
#
#
if [ $UID != "0" ]
then
echo "Not root, Exiting"
echo
exit 1
fi
#
#
#
mkdir -p /etc/vsftpd/vuser
mkdir -p /var/ftp/vuser
#
touch /tmp/vuser_del_tmp
touch /etc/vsftpd/vuser/vuser_list
touch /etc/vsftpd/vuser/vuser_add_bak
touch /etc/vsftpd/vuser/vuser_del
touch /etc/vsftpd/vuser/vuser_del_bak
touch /etc/vsftpd/vuser/vuser_arc
touch /etc/vsftpd/vuser/vuser_arc_bak
touch /etc/vsftpd/vuser/luser_snc
touch /etc/vsftpd/vuser/luser_snc_bak
#
clear
#
cp ./vuser.conf /etc/vsftpd/vuser/vuser.conf
#
echo; echo
if [ -f /etc/vsftpd/vuser/vuser.conf ] 
then
. /etc/vsftpd/vuser/vuser.conf
else
echo "No Config file at /etc/vsftpd/vuser/vuser.conf, error"
echo "Exiting"; echo
exit 1
fi
#
#
echo -n "Vuser Config folder $CONFIG_ROOT "
if [ -d $CONFIG_ROOT ] ; then echo "OK"; else echo "Non Existant"; fi
#
echo -n "File $VUSER_LIST "
if [ -f $CONFIG_ROOT/$VUSER_LIST ] ; then echo "OK"; else echo "Non Existant"; fi
#
echo -n "File $VUSER_DEL "
if [ -f $CONFIG_ROOT/$VUSER_DEL ] ; then echo "OK"; else echo "Non Existant"; fi
#
echo -n "FTP ROOT Folder $VUSER_HOME "
if [ -d $VUSER_HOME ] ; then echo "OK"; else echo "Non Existant"; fi
#
echo
#
echo -n "Install the Berkeley Database Utilities db-util/db4-utils for the scripts to work"
echo
echo -n "VSFTPD Virtual User BASH Scripts copied to /usr/local/bin/"
echo
echo -n "How to Documentation at https://www.howtoforge.com/vsftpd-local-and-virtual-users-with-bash-scripts-for-user-maintenance-centos-6.0"
echo
echo "The scripts:"
echo "vuserchk - checks the necessary files and folders necessary for these scripts"
echo "vuser.conf - the file containing configuration parameters for these scripts"
echo "vuseradd - adds a virtual user"
echo "vuserdel - delets a virtual user"
echo "vuserres - restores a deleted user"
echo "vuserpas - changes a virtual user password"
echo "vusersho - displays the user password"
echo "lusersnc - new script to sync the local user folders with the ftp folders with a symlink in the shell home folder"
echo
echo
#END

